# This file was generated by the {rix} R package v0.13.5 on 2024-12-28
# with following call:
# >rix(r_ver = "6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212",
#  > r_pkgs = c("Seurat"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "scMisc",
#  > repo_url = "https://github.com/mihem/scMisc",
#  > commit = "e2ebddcb779b935551f14216514c0429616fc91d"),
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision 6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212 for reproducibility purposes
# which will install R version 4.4.0.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      languageserver
      Seurat;
  };
 
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "scMisc";
      src = pkgs.fetchgit {
        url = "https://github.com/mihem/scMisc";
        rev = "e2ebddcb779b935551f14216514c0429616fc91d";
        sha256 = "sha256-Atmr+vGfJxNc5HK+UgpnSIeZ1fYKWEzD3Dt2va1xoFE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Seurat
          readr
          glue
          viridis
          ggplot2
          pheatmap
          homologene
          dplyr
          tibble
          magrittr
          clustifyr
          ggrepel
          writexl
          ggsignif
          patchwork
          rstatix
          readxl
          tidyr
          speckle
          limma
          RColorBrewer
          factoextra
          FactoMineR
          Matrix
          ggpubr
          enrichR
          tidyselect
          stringr
          forcats;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages   ];
  
}
